Write a playbook.yml under /home/thor/ansible on jump host, an inventory is already present under /home/thor/ansible directory on Jump host itself. 
Perform below given tasks using this playbook:

We have a file /opt/sysops/blog.txt on app server 1. Using Ansible replace module replace string xFusionCorp to Nautilus in that file.

We have a file /opt/sysops/story.txt on app server 2. Using Ansiblereplace module replace the string Nautilus to KodeKloud in that file.

We have a file /opt/sysops/media.txt on app server 3. Using Ansible replace module replace string KodeKloud to xFusionCorp Industries in that file.

playbook.yml:
---
- name: Replace line in file on App server 1
  hosts: stapp01
  become: yes
  tasks:
  - name: Replace file /opt/sysops/blog.txt
    replace:
      path: /opt/sysops/blog.txt
      regexp: 'xFusionCorp'
      replace: 'Nautilus'
    tags: stapp01


- name: Replace on App server 2
  hosts: stapp02
  become: yes
  tasks:
  - name: Replace file /opt/sysops/story.txt
    replace:
      path: /opt/sysops/story.txt
      regexp: 'Nautilus'
      replace: 'KodeKloud'
    tags: stapp02

- name: Replace on App server 3
  hosts: stapp03
  become: yes
  tasks:
  - name: Replace file /opt/sysops/media.txt
    replace:
      path: /opt/sysops/media.txt
      regexp: 'KodeKloud'
      replace: 'xFusionCorp Industries'
    tags: stapp03