There is already an inventory file ~/playbooks/inventory on jump host.
On jump host itself there is a list of users in ~/playbooks/data/users.yml file and there are two groups — admins and developers —that have list of different users. 
Create a playbook ~/playbooks/add_users.yml on jump host to perform the following tasks on app server 2 in Stratos DC.
a. Add all users given in the users.yml file on app server 2.
b. Also add developers and admins groups on the same server.
c. As per the list given in the users.yml file, make each user member of the respective group they are listed under.
d. Make sure home directory for all of the users under developers group is /var/www (not the default i.e /var/www/{USER}). 
Users under admins group should use the default home directory (i.e /home/devid for user devid).
e. Set password dCV3szSGNA for all of the users under developers group and Rc5C9EyvbU for of the users under admins group. 
Make sure to use the password given in the ~/playbooks/secrets/vault.txt file as Ansible vault password to encrypt the original password strings. 
You can use ~/playbooks/secrets/vault.txt file as a vault secret file while running the playbook (make necessary changes in ~/playbooks/ansible.cfg file).
f. All users under admins group must be added as sudo users. To do so, simply make them member of the wheel group as well.

users.yml:
admins:
  - rob
  - david
  - joy

developers:
  - tim
  - ray
  - jim
  - mark

Add in ansible.cfg : 
-> vault_password_file = /home/thor/playbooks/secrets/vault.txt
Create a file containing all password and encrypt it with vault password (be sure to be in the default ansible.cfg folder to use the vault password :
-> /secrets/secrets.txt : 
admin_password: Rc5C9EyvbU
developer_password: dCV3szSGNA 
-> ansible-vault encrypt secrets/secrets.txt
Output: $ANSIBLE_VAULT;1.1;AES256
36393839343934336434646233646263363837363131623263303136633235633038396532613465
3165346538613566313231303939643532663037333838650a313562656665313861616631626234
61653164616665343766303262373432333835323232353263323037366366366533336630643564
3339626231333366330a346664636230313162303230303364313265333538646237646338393932
38636130353061386636646437633065303637613938393761356237353261363639353565623961
34653863636165646336613634356436616430373038356364363630653965636332393861366663
333533373963313264323831623739643137

add_users.yml:
---
- hosts: stapp02
  become: yes
  vars_files:
  - /home/thor/playbooks/secrets/secrets.txt
  - /home/thor/playbooks/data/users.yml
  tasks:

  - name: Create admins group
    group:
      name: admins
      state: present


  - name: Create developers group
    group: 
      name: developers
      state: present

  - name: Add admins users from users.yml in admins group
    user:
      name: "{{ item }}"
      password: "{{ admin_password | password_hash('sha512') }}"
      home: /home/{{ item }}
      groups: admins, wheel
    with_items: "{{ admins }}"

  - name: Add developers users from users.yml in developers group
    user:
      name: "{{ item }}"
      password: "{{ developer_password | password_hash('sha512') }}"
      create_home: yes
      home: /var/www/
      groups: developers
    with_items: "{{ developers }}"