There is an inventory file ~/playbooks/inventory on jump host.

Create a playbook ~/playbooks/httpd.yml on jump host and perform the following tasks on App Server 3.

a. Install httpd and php packages (whatever default version is available in yum repo).

b. Change default document root of Apache to /var/www/html/myroot in default Apache config /etc/httpd/conf/httpd.conf. 
Make sure /var/www/html/myroot path exists (if not please create the same).

c. There is a template ~/playbooks/templates/phpinfo.php.j2 on jump host. 
Copy this template to the Apache document root you created as phpinfo.php file and make sure user owner and the group owner for this file is apache user.

d. Start and enable httpd service.


httpd.yml:
---
- hosts: stapp03
  become: yes
  tasks:
  - name: Install httpd and php
    yum:
      name:
      - php
      - httpd
      state: latest
    notify:
    - Start and enable httpd service
    tags: install

  - name: Check if new DocumentRoot exists
    file:
      path: /var/www/html/myroot
      state: directory
      owner: apache
      group: apache
    tags: directory

  - name: Change default document root of Apache
    replace:
      path: /etc/httpd/conf/httpd.conf
      regexp: 'DocumentRoot "/var/www/html"'
      replace: 'DocumentRoot "/var/www/html/myroot"'
    tags: replace


  - name: Use template file to Apache
    copy:
      src: /home/thor/playbooks/templates/phpinfo.php.j2
      dest: /var/www/html/myroot/phpinfo.php
      owner: apache
      group: apache

  handlers:
  - name: Start and enable httpd service
    service:
      name: httpd
      state: started
      enabled: yes