Create a pod named volume-share-xfusion.

For the first container, use image fedora with latest tag only and remember to mention the tag i.e fedora:latest, 
container should be named as volume-container-xfusion-1, and run a sleep command for it so that it remains in running state. 
Volume volume-share should be mounted at path /tmp/ecommerce.

For the second container, use image fedora with the latest tag only and remember to mention the tag i.e fedora:latest, 
container should be named as volume-container-xfusion-2, and again run a sleep command for it so that it remains in running state. 
Volume volume-share should be mounted at path /tmp/apps.

Volume name should be volume-share of type emptyDir.

After creating the pod, exec into the first container i.e volume-container-xfusion-1, 
and just for testing create a file ecommerce.txt with any content under the mounted path of first container i.e /tmp/ecommerce.

The file ecommerce.txt should be present under the mounted path /tmp/apps on the second container volume-container-xfusion-2 as well, 
since they are using a shared volume.

/tmp/shared-volume.yml:
apiVersion: v1 
kind: Pod
metadata:
  name: volume-share-xfusion
spec:
  volumes:
    - name: volume-share
      emptyDir: {}
        
  containers:
  - name: volume-container-xfusion-1
    image: fedora:latest
    command: ['bin/sh','-c','sleep 1000']
    volumeMounts:
      - mountPath: /tmp/ecommerce
        name: volume-share

  - name: volume-container-xfusion-2
    image: fedora:latest
    command: ['bin/sh','-c','sleep 1000']
    volumeMounts:
      - mountPath: /tmp/apps
        name: volume-share

kubectl create -f /tmp/shared-volume.yml
kubectl exec -it volume-share-xfusion -c volume-container-xfusion-1 -- /bin/sh
-> Create the file under the mounted path : /tmp/ecommerce/ecommerce.txt
kubectl exec it volume-share-xfusion -c volume-container-xfusion-2 -- cat /tmp/apps/ecommerce.txt