Create a pod called time-check in the devops namespace. This pod should run a container called time-check, container should use the busybox image with latest tag only 
and remember to mention tag i.e busybox:latest.

Create a config map called time-config with the data TIME_FREQ=11 in the same namespace.

The time-check container should run the command: while true; do date; sleep $TIME_FREQ;done and should write the result to the location /opt/finance/time/time-check.log. 
Remember you will also need to add an environmental variable TIME_FREQ in the container, which should pick value from the config map TIME_FREQ key.

Create a volume log-volume and mount the same on /opt/finance/time within the container.

/tmp/time-check.yml:
apiVersion: v1 
kind: ConfigMap
metadata:
  name: time-config
  namespace: devops
data:
    TIME_FREQ: "11"
---
apiVersion: v1 
kind: Pod
metadata:
  name: time-check
  namespace: devops
  labels:
    app: time-check
spec:
  volumes:
  - name: log-volume
    emptyDir: {}
      
  containers:
  - name: time-check
    image: busybox:latest
    volumeMounts:
      - mountPath: /opt/finance/time
        name: log-volume
    command: ['bin/sh','-c']
    args: ["while true; do date; sleep $TIME_FREQ;done > /opt/finance/time/time-check.log"]
    envFrom:
      - configMapRef:
          name: time-config