We already have a secret key file beta.txt under /opt location on jump host. Create a generic secret named beta, it should contain the password/license-number present in beta.txt file.

Also create a pod named secret-nautilus.

Configure pod's spec as container name should be secret-container-nautilus, image should be ubuntu preferably with latest tag (remember to mention the tag with image). 
Use sleep command for container so that it remains in running state. Consume the created secret and mount it under /opt/games within the container.

To verify you can exec into the container secret-container-nautilus, to check the secret key under the mounted path /opt/games. 
Before hitting the Check button please make sure pod/pods are in running state, also validation can take some time to complete so keep patience.

kubectl create secret generic beta --from-file=/opt/beta.txt

/tmp/secret.yml:
apiVersion: v1
kind: Pod
metadata:
  name: secret-nautilus
spec:
  volumes:
  - name: secret-volume-nautilus
    secret:
      secretName: beta

  containers:
  - name: secret-container-nautilus
    image: ubuntu:latest
    command: ["/bin/bash", "-c", "sleep 10000"] 
    volumeMounts:
    - name: secret-volume-nautilus
      mountPath: /opt/games
      readOnly: true

kubectl create -f /tmp/secret.yml
kubectl exec -it secret-nautilus -- cat /opt/games/beta.txt