apiVersion: v1 
kind: PersistentVolume
metadata:
  name: pv-nautilus
spec:
  storageClassName: manual
  accessModes: 
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
      path: /mnt/data
---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: pvc-nautilus
spec:
  storageClassName: manual
  accessModes: 
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1 
kind: Service
metadata:
  name: web-nautilus
spec:
  type: NodePort
  selector:
    app: nautilus
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008
---
apiVersion: v1 
kind: Pod
metadata:
  name: pod-nautilus
spec:
  volumes:
  - name: storage-nautilus
    persistentVolumeClaim:
      claimName: pvc-nautilus
  containers:
  - name: container-nautilus
    image: httpd:latest
    volumeMounts:
    - name: storage-nautilus
      mountPath: /var/www/html
    ports:
    - containerPort: 80
  
    
