Vagrant.configure("2") do |config|
	config.vm.provision :shell , path: "scripts/script.sh"
	config.vm.provision :shell , path: "scripts/jenkins.sh"


	 config.vm.define "jenkins" do |jenkins|
	 	jenkins.vm.box = "ubuntu/bionic64"
	 	jenkins.vm.hostname = "jenkins"
	 	jenkins.vm.network "private_network", ip: "10.10.20.6"
	 	jenkins.vm.provider "virtualbox" do |j|
	 		j.memory = 2048
	 		j.cpus = 2
	 		j.name = "jenkins"
	 	end
	 end

end




